### ISSUE TITLE
Closing Server Should Be Nicer

### ISSUE THREAD

**Issue by Harlantr** [tuchfarber/ThatBeanGame#7]
When closing the server (Ctrl+C), the output is pretty hideous:
```
Traceback (most recent call last):
  File "app/TBG.py", line 262, in <module>
    server.serve_forever()
  File "/home/tom/Development/python/ThatBeanGame/venv/lib/python3.6/site-packages/gevent/baseserver.py", line 362, in serve_forever
    self._stop_event.wait()
  File "/home/tom/Development/python/ThatBeanGame/venv/lib/python3.6/site-packages/gevent/event.py", line 219, in wait
    return self._wait(timeout)
  File "/home/tom/Development/python/ThatBeanGame/venv/lib/python3.6/site-packages/gevent/event.py", line 129, in _wait
    gotit = self._wait_core(timeout)
  File "/home/tom/Development/python/ThatBeanGame/venv/lib/python3.6/site-packages/gevent/event.py", line 106, in _wait_core
    result = self.hub.switch()
  File "/home/tom/Development/python/ThatBeanGame/venv/lib/python3.6/site-packages/gevent/hub.py", line 630, in switch
    return RawGreenlet.switch(self)
KeyboardInterrupt
Makefile:11: recipe for target 'run' failed
make: *** [run] Error 1
```

We should capture the KeyboardInterrupt and end the server cleanly.

**Comment by tuchfarber** [comment]
Fixed with #9
